### ISSUE TITLE
Add LED ring feedback to notifications (use in WiFi onboarding process)

### ISSUE THREAD

**Issue by ubopod** [ubopod/ubo-app#15]
Please refer to the previous implementation of WiFi onboarding for LED patterns used for different phases of on-boading (success scan, success connecting to WiFi, etc)

**Comment by ubopod** [comment]
Here's the doc for current implementation of `rgb_ring` client and service:

https://github.com/ubopod/ubo-sdk/tree/main/rgb_ring

**Comment by mehrdadfeller** [comment]
We can match the notification color to LED ring color and assign different blink patterns based on `IMPORTANCE` level of the notifications. For example `LOW` importance would be one blink, `MEDIUM` would be two blinks, `CRITICAL` would be two blinks. We could potentially introduce other levels and corresponding patterns
