### ISSUE TITLE
Add placeholder to Menu as a required field and show it in MenuWidget

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo-app#26]
Maybe we can show a message or something on an empty page "no networks to select" with back button as part of the message.

**Comment by sassanh** [comment]
It’s a good idea, I also thought about it. We need to add a placeholder property to the `menu`

**Comment by sassanh** [comment]
It’s a good idea, I also thought about it. We need to add a placeholder property to the menu
