### ISSUE TITLE
Turn off backlight where applicable (before power off, etc)

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo-app#41]
The backlight pin is connected to GPIO26 of Raspberry Pi. To turn off the backlight drive, GPIO26 PIN must be set to LOW. To turn on the backlight, drive the pin HIGH.

**Comment by mehrdadfeller** [comment]
BTW, The LITE pin on the schematic below shows the backlight PIN which pull up by a resistor:

https://github.com/ubopod/ubo-pcb?tab=readme-ov-file#lcd

**Comment by sassanh** [comment]
This is implemented a while ago.
