### ISSUE TITLE
app crashes when mic switch on/off is toggled

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo-app#42]
Feb 03 13:29:55 ubo10 ubo[825]: ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
Feb 03 13:29:56 ubo10 ubo[825]: ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
Feb 03 13:30:24 ubo10 ubo[825]: [INFO   ] [Base        ] Leaving application in progress...
Feb 03 13:30:24 ubo10 ubo[825]:  Traceback (most recent call last):
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/bin/ubo", line 8, in <module>
Feb 03 13:30:24 ubo10 ubo[825]:      sys.exit(main())
Feb 03 13:30:24 ubo10 ubo[825]:               ^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/__init__.py", line 58, in main
Feb 03 13:30:24 ubo10 ubo[825]:      app.run()
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/app.py", line 956, in run
Feb 03 13:30:24 ubo10 ubo[825]:      runTouchApp()
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
Feb 03 13:30:24 ubo10 ubo[825]:      EventLoop.mainloop()
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 339, in mainloop
Feb 03 13:30:24 ubo10 ubo[825]:      self.idle()
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 379, in idle
Feb 03 13:30:24 ubo10 ubo[825]:      Clock.tick()
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/clock.py", line 733, in tick
Feb 03 13:30:24 ubo10 ubo[825]:      self.post_idle(ts, self.idle())
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/kivy/clock.py", line 776, in post_idle
Feb 03 13:30:24 ubo10 ubo[825]:      self._process_events()
Feb 03 13:30:24 ubo10 ubo[825]:    File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
Feb 03 13:30:24 ubo10 ubo[825]:    File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
Feb 03 13:30:24 ubo10 ubo[825]:    File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
Feb 03 13:30:24 ubo10 ubo[825]:    File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/store/__init__.py", line 71, in <lambda>
Feb 03 13:30:24 ubo10 ubo[825]:      Clock.create_trigger(lambda _: callback(), 0, interval=interval)()
Feb 03 13:30:24 ubo10 ubo[825]:                                     ^^^^^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/redux/main.py", line 93, in run
Feb 03 13:30:24 ubo10 ubo[825]:      result = reducer(state, action)
Feb 03 13:30:24 ubo10 ubo[825]:               ^^^^^^^^^^^^^^^^^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/redux/combine_reducers.py", line 139, in combined_reducer
Feb 03 13:30:24 ubo10 ubo[825]:      reducers_results = {
Feb 03 13:30:24 ubo10 ubo[825]:                         ^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/redux/combine_reducers.py", line 140, in <dictcomp>
Feb 03 13:30:24 ubo10 ubo[825]:      key: reducer(
Feb 03 13:30:24 ubo10 ubo[825]:           ^^^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-sound/reducer.py", line 82, in reducer
Feb 03 13:30:24 ubo10 ubo[825]:      state=replace(state, is_mic_mute=action.mute),
Feb 03 13:30:24 ubo10 ubo[825]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:    File "/usr/lib/python3.11/dataclasses.py", line 1491, in replace
Feb 03 13:30:24 ubo10 ubo[825]:      return obj.__class__(**changes)
Feb 03 13:30:24 ubo10 ubo[825]:             ^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 13:30:24 ubo10 ubo[825]:  TypeError: SoundState.__init__() got an unexpected keyword argument 'is_mic_mute'

**Comment by sassanh** [comment]
It's fixed in version 0.9.7
