### ISSUE TITLE
Docker Apps: Show web dashboard URL with QR code after starting a container with a web portal

### ISSUE THREAD

**Issue by ubopod** [ubopod/ubo-app#47]
After fetching and starting a docker container, we should show a QR code that contains the link for the Web Dashboard/Portal for the corresponding docker based service. The user simply scans the QR code to access the dashboard. If we use an ingress service like `ngrok`, we can make the URL based on that as well (rather than local network IP address & port).

**Comment by sassanh** [comment]
This is implemented. extracting the ngrok urls is not straightforward and brings more complexity to our docker engine.
