### ISSUE TITLE
docker start on GUI is not doing anything (v0.11.6)

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo-app#54]
When I press docker start, the screen tries to show something quickly but nothing happens after that. I don't see any errors in `ubo-app.log`. I only see the command is send in `system-manager.log`:

```
ubo@raspberrypi:/opt/ubo $ tail -f system-manager.log

1711586657.486268 [DEBUG] New connection: - extra: {
    "client_address": ""
}
1711586657.487705 [DEBUG] Received command: - extra: {
    "command": "b'docker start'"
}
```

**Comment by sassanh** [comment]
@mehrdadfeller Please test it again in 12.0.0, it seems to be working for me.

**Comment by sassanh** [comment]
I just ran Portainer and connected to it without any issues, I also stopped and started docker service via our GUI several times, I think this issue is resolved by itself.
